### ISSUE TITLE
error: implicit instantiation of undefined template 'std::__1::array<VkImageView_T *, 3>'

### ISSUE THREAD

**Issue by yurivict** [Brenocq/Atta#4]
clang-10 complains:
```
                std::array<VkImageView, 3> attachments = {
                                           ^
/usr/include/c++/v1/__tuple:219:64: note: template is declared here
template <class _Tp, size_t _Size> struct _LIBCPP_TEMPLATE_VIS array;
                                                               ^
1 error generated.
```

Did you forget to include ```<array>```?

Same in src/simulator/graphics/vulkan/descriptorSetLayout.cpp
Same in src/simulator/graphics/vulkan/renderPass.cpp

**Comment by Brenocq** [comment]
The current master branch code has been refactored and no longer generates this error when compiling with clang (tested with clang-12).
Thanks.
