### ISSUE TITLE
Project doesn't install anything

### ISSUE THREAD

**Issue by yurivict** [Brenocq/Atta#6]
Please add the ```install``` target.

The executable ```atta``` throws exception when run alone, so it probably expects some other files.

**Comment by Brenocq** [comment]
Thank you, I just updated the atta AUR package to generate the atta executable.

**Comment by yurivict** [comment]
But installation is supposed to be done 100% from inside of the project. The atta AUR port shouldn't run the ```install``` command.

**Comment by Brenocq** [comment]
Oh, thanks for letting me know, I really appreciate it. Sorry about that, I just started with cmake and AUR packages... I'm going to reopen this issue and study more about it.
I recreated the cmake file and the pkgbuild file in the past few days, if you find something strange there, please tell me.
Thanks!

**Comment by Brenocq** [comment]
Hi, now the project is installing the `atta` and `atta_test` executables. I'm closing this issue, if you find anything wrong with the new build, please let me know. Thank you!
