### ISSUE TITLE
hide tab bar doesn't actually hide the tab

### ISSUE THREAD

**Issue by diksown** [brenocq/atta#7]
Before:
![image](https://user-images.githubusercontent.com/49994083/142343269-764c3765-4029-4eef-b27c-8aeb8cf423ac.png)

After:
![image](https://user-images.githubusercontent.com/49994083/142343326-6b55e48d-eeb2-4752-8536-911bbd37046c.png)

**Comment by brenocq** [comment]
Thank you for submitting the issue! On the following days I will redo the UI windows to not show the "Hide tab bar" button.

**Comment by brenocq** [comment]
The "Hide tab bar" menu was removed in commit 0ad61f15d51dc68fd176a35aa70d3d871db8e72d, thanks again for your feedback 😃 
![DeepinScreenshot_select-area_20211204120103](https://user-images.githubusercontent.com/17342434/144714360-a2c72851-3c6e-4abf-8529-26e7622941a4.png)
